name: Testseite Nummer 1
favicon: null
layout_spectrum: 0.21628
typography_spectrum: 0.9388430425897241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.875
  lightness: 0.3027851553633809
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
