name: Testseite Nummer 1
favicon: null
layout_spectrum: 0.464567253831774
typography_spectrum: 0.9388430425897241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6035247538238764
  lightness: 0.3027851553633809
  saturation: 0.8699801845941693
  rhythmicContrast: 0.22637164522893727
purpose: []
